version: '3.8'

services:
  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: partiucorrer_db
    restart: always
    environment:
      MYSQL_DATABASE: partiucorrer
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: partiucorrer_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=partiucorrer
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=meu_segredo_super_seguro
      - VAPID_PUBLIC_KEY=BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuB-5qHjXm-9Z-H3O5DqgHj-V0
      - VAPID_PRIVATE_KEY=aXzS6S_H3O5DqgHj-V0BEl62iUYgUivxIkv69yViEui
      - VAPID_SUBJECT=mailto:admin@partiucorrer.com
    depends_on:
      - db
    networks:
      - app_network

  # Frontend React (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: partiucorrer_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
